// <auto-generated />
namespace CodingTrainer.CodingTrainerEntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddAssessmentMessagesEtc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAssessmentMessagesEtc));
        
        string IMigrationMetadata.Id
        {
            get { return "201905031454545_AddAssessmentMessagesEtc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
